name: Build and Deploy PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get install -y texlive-xetex
    
    - name: Copy texmf folder
      run: |
        if [ -d "texmf" ]; then
          cp -r texmf $GITHUB_WORKSPACE
        fi

    - name: Build PDF
      working-directory: ${{ github.workspace }}
      run: |
        xelatex -interaction=nonstopmode -halt-on-error main.tex
        mv main.pdf $GITHUB_WORKSPACE/output.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: $GITHUB_WORKSPACE
