name: Build and Deploy PDF

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up latex2pdf
      uses: thomas-chauvet/latex2pdf-action@1.0.5
      with:
        output_dir: output
        main_latex_file: main.tex
        ctan_packages: amsmath amsfonts physics


    - name: Upload PDF to the workflow tab
      id: upload-workflow-tab
      uses: actions/upload-artifact@v2
      with:
          name: output
          path: output/test.pdf
